/*
 * File: app/view/AuthorityTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.AuthorityTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.authoritytab',

    requires: [
        'TabUserInformation.view.AuthorityTabViewModel',
        'TabUserInformation.view.AuthorityTabViewController',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.View',
        'Ext.grid.plugin.RowEditing'
    ],

    controller: 'authoritytab',
    viewModel: {
        type: 'authoritytab'
    },
    title: 'Authority',

    items: [
        {
            xtype: 'panel',
            height: 84,
            bodyPadding: '',
            title: 'ค้นหา',
            layout: {
                type: 'hbox',
                align: 'middle'
            },
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Search Text',
                    labelAlign: 'right'
                },
                {
                    xtype: 'button',
                    margin: '0 0 0 5',
                    text: 'Search',
                    listeners: {
                        click: 'onButtonSearchClick'
                    }
                }
            ]
        },
        {
            xtype: 'form',
            bodyPadding: 10,
            title: 'My Form',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Add',
                            listeners: {
                                click: 'onButtonAddClick'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Save',
                            listeners: {
                                click: 'onButtonSaveClick'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Delete',
                            listeners: {
                                click: 'onButtonDeleteClick'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            title: 'My Grid Panel',
            store: 'authorities',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 64,
                    text: 'Row',
                    flex: 0
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'id',
                    text: 'Id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'myField',
                    text: 'MyField',
                    flex: -1,
                    editor: {
                        xtype: 'textfield'
                    }
                }
            ],
            plugins: [
                {
                    ptype: 'rowediting'
                }
            ]
        }
    ]

});