/*
 * File: app/view/CusInfTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.CusInfTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.cusinftab',

    requires: [
        'TabUserInformation.view.CusInfTabViewModel',
        'TabUserInformation.view.CusInfTabViewController',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    controller: 'cusinftab',
    viewModel: {
        type: 'cusinftab'
    },
    width: '100%',
    title: 'Customer Information',

    items: [
        {
            xtype: 'panel',
            height: 84,
            bodyPadding: '',
            title: 'ค้นหา',
            layout: {
                type: 'hbox',
                align: 'middle'
            },
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Search Text',
                    labelAlign: 'right'
                },
                {
                    xtype: 'button',
                    margin: '0 0 0 5',
                    text: 'Search',
                    listeners: {
                        click: 'onButtonSearchClick'
                    }
                },
                {
                    xtype: 'radiogroup',
                    width: 300,
                    layout: {
                        type: 'checkboxgroup',
                        autoFlex: false
                    },
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: 'Code'
                        },
                        {
                            xtype: 'radiofield',
                            margin: '0 0 0 5',
                            boxLabel: 'English Name'
                        },
                        {
                            xtype: 'radiofield',
                            margin: '0 0 0 5',
                            boxLabel: 'Thai Name'
                        }
                    ]
                },
                {
                    xtype: 'checkboxfield',
                    flex: 0,
                    boxLabel: 'Partial'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            autoScroll: true,
            height: 500,
            title: 'Customer Information',
            store: 'customerInformations',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Code',
                    text: 'Code'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Name Eng',
                    text: 'Name Eng'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Name Thai',
                    text: 'Name Thai'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'customerInformations'
                }
            ]
        },
        {
            xtype: 'panel',
            bodyPadding: 20,
            manageHeight: false,
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Industry Code'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Nature of Cust'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Group of Cust'
                },
                {
                    xtype: 'container',
                    height: 30,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Telephone'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Fax',
                            labelAlign: 'right',
                            labelWidth: 50
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    width: 400,
                    fieldLabel: 'Email Address',
                    inputType: 'email'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Warning'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Status'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Inactive Reason'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Exit',
                            listeners: {
                                exit: 'onButtonExit11'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Edit',
                            listeners: {
                                click: 'onButtonEditClick1'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});