/*
 * File: app/view/CusInfWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.CusInfWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.cusinfwindow',

    requires: [
        'TabUserInformation.view.CusInfWindowViewModel',
        'TabUserInformation.view.CusInfWindowViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.form.FieldContainer',
        'Ext.form.field.Number',
        'Ext.form.FieldSet',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View'
    ],

    controller: 'cusinfwindow',
    viewModel: {
        type: 'cusinfwindow'
    },
    height: 820,
    layout: 'anchor',
    title: 'Customer Information',
    titleCollapse: false,

    items: [
        {
            xtype: 'panel',
            width: 925,
            animCollapse: false,
            bodyPadding: 20,
            collapsible: true,
            title: 'Information',
            titleCollapse: false,
            layout: {
                type: 'table',
                columns: 3
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Address'
                        },
                        {
                            xtype: 'button',
                            text: 'Signer'
                        },
                        {
                            xtype: 'button',
                            text: 'Contact Person'
                        },
                        {
                            xtype: 'button',
                            text: 'Affidavit'
                        },
                        {
                            xtype: 'button',
                            text: 'Power of Attorney'
                        },
                        {
                            xtype: 'button',
                            text: 'Company Seal'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Customer Code',
                    labelWidth: 150
                },
                {
                    xtype: 'container',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'combobox',
                            margin: '0 0 0 5',
                            width: 200,
                            fieldLabel: 'Type of Customer',
                            labelWidth: 110
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: '0 0 0 5',
                            text: 'History'
                        }
                    ]
                },
                {
                    xtype: 'combobox',
                    margin: '0 0 0 5',
                    fieldLabel: 'Industry Code'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Customer Eng Name',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    width: 270
                },
                {
                    xtype: 'combobox',
                    margin: '0 0 0 5',
                    fieldLabel: 'Nature of Cus'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Customer Thai Name',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    width: 270
                },
                {
                    xtype: 'combobox',
                    margin: '0 0 0 5',
                    fieldLabel: 'Group of Cus'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Parent Country',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    margin: '0 0 0 5',
                    width: 270,
                    fieldLabel: 'Telephone'
                },
                {
                    xtype: 'textfield',
                    margin: '0 0 0 5',
                    fieldLabel: 'Fax'
                },
                {
                    xtype: 'combobox',
                    fieldLabel: 'Email',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    margin: '0 0 0 5',
                    width: 270,
                    fieldLabel: 'Tax No'
                },
                {
                    xtype: 'textfield',
                    margin: '0 5 0 5',
                    fieldLabel: 'VAT %'
                }
            ]
        },
        {
            xtype: 'panel',
            width: 925,
            animCollapse: false,
            bodyPadding: 20,
            collapsible: true,
            title: 'Background',
            layout: {
                type: 'table',
                columns: 3
            },
            items: [
                {
                    xtype: 'container',
                    colspan: 3,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textfield',
                            width: 600,
                            fieldLabel: 'Business',
                            labelWidth: 150
                        },
                        {
                            xtype: 'button',
                            margin: '0 5 0 5',
                            text: 'Shareholder\'s'
                        }
                    ]
                },
                {
                    xtype: 'datefield',
                    fieldLabel: 'Establishment',
                    labelWidth: 150
                },
                {
                    xtype: 'fieldcontainer',
                    width: 400,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'numberfield',
                            flex: 1,
                            margin: '0 0 0 5',
                            width: 180,
                            fieldLabel: 'Stock PR'
                        },
                        {
                            xtype: 'datefield',
                            flex: 1,
                            margin: '0 0 0 5',
                            fieldLabel: 'As Of'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    colspan: 2,
                    layout: 'hbox'
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Register Capital',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    colspan: 2,
                    width: 500,
                    fieldLabel: ''
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Sales',
                    labelWidth: 150
                },
                {
                    xtype: 'container',
                    colspan: 2,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textfield',
                            margin: '0 0 0 5',
                            width: 180,
                            fieldLabel: 'Year',
                            labelWidth: 50
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            margin: '0 0 0 5'
                        }
                    ]
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Profit (Loss)',
                    labelWidth: 150
                },
                {
                    xtype: 'container',
                    colspan: 2,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textfield',
                            margin: '0 0 0 5',
                            width: 180,
                            fieldLabel: 'Year',
                            labelWidth: 50
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            margin: '0 0 0 5'
                        }
                    ]
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Shareholder\'s Equity',
                    labelWidth: 150
                },
                {
                    xtype: 'container',
                    colspan: 2,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textfield',
                            margin: '0 0 0 5',
                            width: 180,
                            fieldLabel: 'Year',
                            labelWidth: 50
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            margin: '0 0 0 5'
                        }
                    ]
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Outstanding Amount',
                    labelWidth: 150
                },
                {
                    xtype: 'datefield',
                    colspan: 2,
                    margin: '0 0 0 5',
                    width: 180,
                    fieldLabel: 'As Of',
                    labelWidth: 50
                },
                {
                    xtype: 'numberfield',
                    fieldLabel: 'Exposure Limit',
                    labelWidth: 150
                },
                {
                    xtype: 'container',
                    colspan: 2,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'datefield',
                            flex: 1,
                            margin: '0 0 0 5',
                            fieldLabel: 'As Of',
                            labelWidth: 50
                        },
                        {
                            xtype: 'combobox',
                            flex: 1,
                            margin: '0 0 0 5'
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: '0 0 0 5',
                            text: 'Background History'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            width: 925,
            layout: {
                type: 'table',
                columns: 2
            },
            items: [
                {
                    xtype: 'panel',
                    width: 521,
                    bodyPadding: 20,
                    items: [
                        {
                            xtype: 'container',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'KTIBJ Marketing Officer',
                                    labelWidth: 150
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 0 0 5',
                                    text: '...'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 0 0 5',
                                    text: 'History'
                                }
                            ]
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Warning',
                            labelWidth: 150
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Status',
                            labelWidth: 150
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Credit Analysis Report'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Others Report'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Business Online'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Method of Payment'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    height: 144,
                    margin: '0 0 0 10',
                    width: 300,
                    anchorSize: 50,
                    layout: 'auto',
                    title: 'Due Day',
                    items: [
                        {
                            xtype: 'gridpanel',
                            height: '100%',
                            width: '100%',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'String'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Number'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'Date'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Boolean'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            width: 925,
            items: [
                {
                    xtype: 'button',
                    text: 'Exit',
                    listeners: {
                        exit: 'onButtonExit11'
                    }
                },
                {
                    xtype: 'button',
                    text: 'Save',
                    listeners: {
                        click: 'onButtonNewClick1'
                    }
                },
                {
                    xtype: 'button',
                    text: 'Cancel',
                    listeners: {
                        click: 'onButtonEditClick1'
                    }
                }
            ]
        }
    ]

});