/*
 * File: app/view/SetupTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.view.SetupTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.setuptab',

    requires: [
        'TabUserInformation.view.SetupTabViewModel',
        'TabUserInformation.view.SetupTabViewController',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.View',
        'Ext.grid.feature.Grouping',
        'Ext.toolbar.Paging'
    ],

    controller: 'setuptab',
    viewModel: {
        type: 'setuptab'
    },
    title: 'Setup',

    items: [
        {
            xtype: 'panel',
            height: 84,
            bodyPadding: '',
            title: 'ค้นหา',
            layout: {
                type: 'hbox',
                align: 'middle'
            },
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Search Text',
                    labelAlign: 'right'
                },
                {
                    xtype: 'button',
                    margin: '0 0 0 5',
                    text: 'Search',
                    listeners: {
                        click: 'onButtonSearchClick1'
                    }
                }
            ]
        },
        {
            xtype: 'gridpanel',
            title: 'Data',
            store: 'setups',
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 64,
                    text: 'Row',
                    flex: 0
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'id',
                    text: 'Id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'myField',
                    text: 'MyField',
                    flex: -1,
                    editor: {
                        xtype: 'textfield'
                    }
                }
            ],
            features: [
                {
                    ftype: 'grouping'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Add',
                            listeners: {
                                click: 'onButtonAddClick1'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Save',
                            listeners: {
                                click: 'onButtonSaveClick1'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Delete',
                            listeners: {
                                click: 'onButtonDeleteClick1'
                            }
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'setups'
                }
            ]
        }
    ]

});