using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using FluentNHibernate.Mapping;
using KTBLeasing.Domain;


namespace KTBLeasing.Mappings.FluentNh
{
    public class BatchtbMap : ClassMap<Batchtb>
    {
        public BatchtbMap()
        {
            Table("batchtb");
            LazyLoad();
            CompositeId().KeyProperty(x => x.ComId, "COM_ID")
                         .KeyProperty(x => x.Agrcode, "AGRCODE")
                         .KeyProperty(x => x.BatchDd, "BATCH_DD");
            Map(x => x.Cuscode).Column("CUSCODE").Not.Nullable();
            Map(x => x.CreateDt).Column("CREATE_DT").Not.Nullable();
            Map(x => x.Cost).Column("COST").Not.Nullable();
            Map(x => x.OriAr).Column("ORI_AR").Not.Nullable();
            Map(x => x.OsAr).Column("OS_AR").Not.Nullable();
            Map(x => x.OsPr).Column("OS_PR").Not.Nullable();
            Map(x => x.OsPrC).Column("OS_PR_C").Not.Nullable();
            Map(x => x.UnpaidVat).Column("UNPAID_VAT").Not.Nullable();
            Map(x => x.LastPaidDd).Column("LAST_PAID_DD");
            Map(x => x.InstPaid).Column("INST_PAID").Not.Nullable();
            Map(x => x.Install).Column("INSTALL").Not.Nullable();
            Map(x => x.InstVat).Column("INST_VAT").Not.Nullable();
            Map(x => x.Penalty).Column("PENALTY").Not.Nullable();
            Map(x => x.LateMax).Column("LATE_MAX").Not.Nullable();
            Map(x => x.OdueFm).Column("ODUE_FM").Not.Nullable();
            Map(x => x.Late7).Column("LATE_7").Not.Nullable();
            Map(x => x.Late30).Column("LATE_30").Not.Nullable();
            Map(x => x.Late60).Column("LATE_60").Not.Nullable();
            Map(x => x.Late90).Column("LATE_90").Not.Nullable();
            Map(x => x.Late180).Column("LATE_180").Not.Nullable();
            Map(x => x.Late180U).Column("LATE_180U").Not.Nullable();
            Map(x => x.LateAll).Column("LATE_ALL").Not.Nullable();
            Map(x => x.LateAllVat).Column("LATE_ALL_VAT").Not.Nullable();
            Map(x => x.StopI).Column("STOP_I");
            Map(x => x.Dateend).Column("DATEEND");
            Map(x => x.WoDd).Column("WO_DD");
            Map(x => x.Product).Column("PRODUCT").Not.Nullable();
            Map(x => x.Dept).Column("DEPT").Not.Nullable();
            Map(x => x.Zip).Column("ZIP").Not.Nullable();
            Map(x => x.Province).Column("PROVINCE").Not.Nullable();
            Map(x => x.Region).Column("REGION").Not.Nullable();
            Map(x => x.Cusname).Column("CUSNAME").Not.Nullable();
            Map(x => x.CusAdr1).Column("CUS_ADR1").Not.Nullable();
            Map(x => x.CusTel1).Column("CUS_TEL1").Not.Nullable();
            Map(x => x.Contact1).Column("CONTACT1").Not.Nullable();
            Map(x => x.CusAdr2).Column("CUS_ADR2").Not.Nullable();
            Map(x => x.CusTel2).Column("CUS_TEL2").Not.Nullable();
            Map(x => x.Contact2).Column("CONTACT2").Not.Nullable();
            Map(x => x.CusAdr3).Column("CUS_ADR3").Not.Nullable();
            Map(x => x.CusTel3).Column("CUS_TEL3").Not.Nullable();
            Map(x => x.Contact3).Column("CONTACT3").Not.Nullable();
            Map(x => x.G1).Column("G1").Not.Nullable();
            Map(x => x.G1Adr).Column("G1_ADR").Not.Nullable();
            Map(x => x.G1Tel).Column("G1_TEL").Not.Nullable();
            Map(x => x.G2).Column("G2").Not.Nullable();
            Map(x => x.G2Adr).Column("G2_ADR").Not.Nullable();
            Map(x => x.G2Tel).Column("G2_TEL").Not.Nullable();
            Map(x => x.G3).Column("G3").Not.Nullable();
            Map(x => x.G3Adr).Column("G3_ADR").Not.Nullable();
            Map(x => x.G3Tel).Column("G3_TEL").Not.Nullable();
            Map(x => x.G4).Column("G4").Not.Nullable();
            Map(x => x.G4Adr).Column("G4_ADR").Not.Nullable();
            Map(x => x.G4Tel).Column("G4_TEL").Not.Nullable();
            Map(x => x.Tr).Column("TR").Not.Nullable();
            Map(x => x.TrFrom).Column("TR_FROM").Not.Nullable();
            Map(x => x.TrTo).Column("TR_TO").Not.Nullable();
            Map(x => x.G1Name).Column("G1_NAME").Not.Nullable();
            Map(x => x.G2Name).Column("G2_NAME").Not.Nullable();
            Map(x => x.G3Name).Column("G3_NAME").Not.Nullable();
            Map(x => x.G4Name).Column("G4_NAME").Not.Nullable();
            Map(x => x.ComDd).Column("COM_DD");
            Map(x => x.First).Column("FIRST");
            Map(x => x.DueDay).Column("DUE_DAY").Not.Nullable();
            Map(x => x.Terms).Column("TERMS").Not.Nullable();
            Map(x => x.LastDd).Column("LAST_DD");
            Map(x => x.TermDd).Column("TERM_DD");
            Map(x => x.TypeEnt).Column("TYPE_ENT").Not.Nullable();
            Map(x => x.Activity).Column("ACTIVITY");
            Map(x => x.Age).Column("AGE").Not.Nullable();
            Map(x => x.Collect).Column("COLLECT");
            Map(x => x.MktExe).Column("MKT_EXE");
            Map(x => x.MktName).Column("MKT_NAME").Not.Nullable();
            Map(x => x.Typefin).Column("TYPEFIN").Not.Nullable();
            Map(x => x.Lease).Column("LEASE").Not.Nullable();
            Map(x => x.MetPay).Column("MET_PAY").Not.Nullable();
            Map(x => x.IntQuo).Column("INT_QUO").Not.Nullable();
            Map(x => x.Eff1).Column("EFF1").Not.Nullable();
            Map(x => x.Eff2).Column("EFF2").Not.Nullable();
            Map(x => x.Supcode).Column("SUPCODE");
            Map(x => x.Supname).Column("SUPNAME").Not.Nullable();
            Map(x => x.Asset).Column("ASSET").Not.Nullable();
            Map(x => x.Brand).Column("BRAND");
            Map(x => x.Chassis).Column("CHASSIS");
            Map(x => x.EngSer).Column("ENG_SER");
            Map(x => x.Licence).Column("LICENCE");
            Map(x => x.Eqpcode).Column("EQPCODE");
            Map(x => x.Eqpdesc).Column("EQPDESC").Not.Nullable();
            Map(x => x.Finance).Column("FINANCE").Not.Nullable();
            Map(x => x.FinVat).Column("FIN_VAT").Not.Nullable();
            Map(x => x.Cat9).Column("CAT9");
            Map(x => x.Comm).Column("COMM").Not.Nullable();
            Map(x => x.Deduct).Column("DEDUCT").Not.Nullable();
            Map(x => x.InstNo).Column("INST_NO").Not.Nullable();
            Map(x => x.MktStatus).Column("MKT_STATUS").Not.Nullable();
            Map(x => x.MktArea).Column("MKT_AREA").Not.Nullable();
            Map(x => x.EmpId).Column("EMP_ID").Not.Nullable();
            Map(x => x.CommOdueFm).Column("COMM_ODUE_FM").Not.Nullable();
            Map(x => x.CommInstNo).Column("COMM_INST_NO").Not.Nullable();
            Map(x => x.CommOdue).Column("COMM_ODUE").Not.Nullable();
            Map(x => x.Mobile).Column("MOBILE").Not.Nullable();
            Map(x => x.AgrSts).Column("agr_sts").Not.Nullable();
            Map(x => x.Ktbsalary).Column("KTBSALARY").Not.Nullable();
            Map(x => x.Profit).Column("PROFIT").Not.Nullable();
            Map(x => x.Model).Column("MODEL");
            Map(x => x.LateMaxPrv).Column("LATE_MAX_PRV");
            Map(x => x.LateMaxNxt).Column("LATE_MAX_NXT");
            Map(x => x.CostVat).Column("COST_VAT").Not.Nullable();
            Map(x => x.Down).Column("DOWN").Not.Nullable();
            Map(x => x.DownVat).Column("DOWN_VAT").Not.Nullable();
            Map(x => x.Depo).Column("DEPO").Not.Nullable();
            Map(x => x.DepoVat).Column("DEPO_VAT").Not.Nullable();
            Map(x => x.Income).Column("INCOME").Not.Nullable();
            Map(x => x.RegionDesc).Column("REGION_DESC");
            Map(x => x.ActivityDesc).Column("ACTIVITY_DESC");
            Map(x => x.MetPayTxt).Column("MET_PAY_TXT");
            Map(x => x.A01).Column("A01");
            Map(x => x.A10).Column("A10");
            Map(x => x.R).Column("R");
            Map(x => x.Comcode).Column("COMCODE").Not.Nullable();
            Map(x => x.OdueTo).Column("ODUE_TO");
            Map(x => x.OdueFmDd).Column("ODUE_FM_DD");
            Map(x => x.OdueToDd).Column("ODUE_TO_DD");
            Map(x => x.NoOdue).Column("NO_ODUE");
            Map(x => x.DnOuts).Column("DN_OUTS");
            Map(x => x.DnVatOuts).Column("DN_VAT_OUTS");
            Map(x => x.Remain).Column("REMAIN");
            Map(x => x.TitleT).Column("TITLE_T");
            Map(x => x.OsPrOld).Column("OS_PR_OLD");
            Map(x => x.OsPrCOld).Column("OS_PR_C_OLD");
            Map(x => x.Cbsaccount).Column("CBSACCOUNT");
            Map(x => x.WoPrin).Column("WO_PRIN");
            Map(x => x.BirthDd).Column("BIRTH_DD");
            Map(x => x.BranchK).Column("BRANCH_K");
            Map(x => x.CrExe).Column("CR_EXE");
            Map(x => x.OsArVat).Column("OS_AR_VAT");
        }
    }
}
