/*
 * File: app/store/customerInformations.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.store.customerInformations', {
    extend: 'Ext.data.Store',
    alias: 'store.customerinformations',

    requires: [
        'TabUserInformation.model.CustomerInformation',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'customerInformations',
            model: 'TabUserInformation.model.CustomerInformation',
            data: [
                {
                    Code: 'dolorum',
                    'Name Eng': 'sunt',
                    'Name Thai': 'eum'
                },
                {
                    Code: 'praesentium',
                    'Name Eng': 'odit',
                    'Name Thai': 'sequi'
                },
                {
                    Code: 'veritatis',
                    'Name Eng': 'sit',
                    'Name Thai': 'possimus'
                },
                {
                    Code: 'non',
                    'Name Eng': 'facilis',
                    'Name Thai': 'beatae'
                },
                {
                    Code: 'est',
                    'Name Eng': 'praesentium',
                    'Name Thai': 'ut'
                },
                {
                    Code: 'quia',
                    'Name Eng': 'vel',
                    'Name Thai': 'corrupti'
                },
                {
                    Code: 'fuga',
                    'Name Eng': 'omnis',
                    'Name Thai': 'deleniti'
                },
                {
                    Code: 'velit',
                    'Name Eng': 'aut',
                    'Name Thai': 'sit'
                },
                {
                    Code: 'aut',
                    'Name Eng': 'sit',
                    'Name Thai': 'ut'
                },
                {
                    Code: 'officia',
                    'Name Eng': 'veniam',
                    'Name Thai': 'velit'
                },
                {
                    Code: 'officia',
                    'Name Eng': 'nemo',
                    'Name Thai': 'suscipit'
                },
                {
                    Code: 'et',
                    'Name Eng': 'nostrum',
                    'Name Thai': 'adipisci'
                },
                {
                    Code: 'placeat',
                    'Name Eng': 'qui',
                    'Name Thai': 'minus'
                },
                {
                    Code: 'ratione',
                    'Name Eng': 'atque',
                    'Name Thai': 'error'
                },
                {
                    Code: 'eum',
                    'Name Eng': 'eos',
                    'Name Thai': 'quis'
                },
                {
                    Code: 'fugiat',
                    'Name Eng': 'omnis',
                    'Name Thai': 'et'
                },
                {
                    Code: 'adipisci',
                    'Name Eng': 'consequatur',
                    'Name Thai': 'quaerat'
                },
                {
                    Code: 'eaque',
                    'Name Eng': 'quia',
                    'Name Thai': 'deserunt'
                },
                {
                    Code: 'qui',
                    'Name Eng': 'et',
                    'Name Thai': 'consequatur'
                },
                {
                    Code: 'rerum',
                    'Name Eng': 'magni',
                    'Name Thai': 'molestiae'
                },
                {
                    Code: 'labore',
                    'Name Eng': 'rerum',
                    'Name Thai': 'maiores'
                },
                {
                    Code: 'sed',
                    'Name Eng': 'minima',
                    'Name Thai': 'dolores'
                },
                {
                    Code: 'qui',
                    'Name Eng': 'corporis',
                    'Name Thai': 'qui'
                },
                {
                    Code: 'consequatur',
                    'Name Eng': 'omnis',
                    'Name Thai': 'hic'
                },
                {
                    Code: 'quisquam',
                    'Name Eng': 'ut',
                    'Name Thai': 'delectus'
                },
                {
                    Code: 'ullam',
                    'Name Eng': 'blanditiis',
                    'Name Thai': 'omnis'
                },
                {
                    Code: 'ea',
                    'Name Eng': 'voluptas',
                    'Name Thai': 'ipsa'
                },
                {
                    Code: 'architecto',
                    'Name Eng': 'molestiae',
                    'Name Thai': 'qui'
                },
                {
                    Code: 'veritatis',
                    'Name Eng': 'dolorum',
                    'Name Thai': 'in'
                },
                {
                    Code: 'est',
                    'Name Eng': 'voluptatem',
                    'Name Thai': 'aut'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});