/*
 * File: app/store/userInformations.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabUserInformation.store.userInformations', {
    extend: 'Ext.data.Store',
    alias: 'store.userinformations',

    requires: [
        'TabUserInformation.model.UserInformation',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'userInformations',
            model: 'TabUserInformation.model.UserInformation',
            data: [
                {
                    id: 911,
                    Code: 'aliquid',
                    Title: 'Rerum Necessitatibus Et Ducimus Voluptatem',
                    Name: 'quidem',
                    Position: 'dolore',
                    MarketingGroup: 'praesentium',
                    MarketingCode: 'voluptatem',
                    Department: 'reprehenderit'
                },
                {
                    id: 900,
                    Code: 'laudantium',
                    Title: 'Eaque Minima',
                    Name: 'sint',
                    Position: 'modi',
                    MarketingGroup: 'soluta',
                    MarketingCode: 'qui',
                    Department: 'libero'
                },
                {
                    id: 604,
                    Code: 'necessitatibus',
                    Title: 'Error Cupiditate Id Qui At',
                    Name: 'ut',
                    Position: 'assumenda',
                    MarketingGroup: 'veniam',
                    MarketingCode: 'non',
                    Department: 'eum'
                },
                {
                    id: 888,
                    Code: 'et',
                    Title: 'Sint Quia Qui Voluptates Maxime',
                    Name: 'adipisci',
                    Position: 'porro',
                    MarketingGroup: 'maiores',
                    MarketingCode: 'labore',
                    Department: 'veniam'
                },
                {
                    id: 636,
                    Code: 'at',
                    Title: 'Animi Beatae Voluptas Animi Error',
                    Name: 'animi',
                    Position: 'aut',
                    MarketingGroup: 'ex',
                    MarketingCode: 'hic',
                    Department: 'ipsum'
                },
                {
                    id: 951,
                    Code: 'voluptatem',
                    Title: 'Sint Nisi Vel Sunt Doloremque',
                    Name: 'dignissimos',
                    Position: 'provident',
                    MarketingGroup: 'veritatis',
                    MarketingCode: 'voluptates',
                    Department: 'nemo'
                },
                {
                    id: 321,
                    Code: 'quia',
                    Title: 'Voluptatum Ducimus',
                    Name: 'voluptates',
                    Position: 'architecto',
                    MarketingGroup: 'enim',
                    MarketingCode: 'ea',
                    Department: 'voluptas'
                },
                {
                    id: 261,
                    Code: 'optio',
                    Title: 'Eos Quaerat In Corrupti Suscipit',
                    Name: 'sint',
                    Position: 'placeat',
                    MarketingGroup: 'culpa',
                    MarketingCode: 'facere',
                    Department: 'facere'
                },
                {
                    id: 93,
                    Code: 'ut',
                    Title: 'Omnis Fugit',
                    Name: 'veniam',
                    Position: 'consequuntur',
                    MarketingGroup: 'dolore',
                    MarketingCode: 'commodi',
                    Department: 'magni'
                },
                {
                    id: 756,
                    Code: 'odit',
                    Title: 'Earum Quasi Mollitia Magni Quae',
                    Name: 'nisi',
                    Position: 'sed',
                    MarketingGroup: 'cumque',
                    MarketingCode: 'quam',
                    Department: 'blanditiis'
                },
                {
                    id: 545,
                    Code: 'nobis',
                    Title: 'Cumque Ea Laboriosam Sed Praesentium',
                    Name: 'sunt',
                    Position: 'id',
                    MarketingGroup: 'modi',
                    MarketingCode: 'et',
                    Department: 'ut'
                },
                {
                    id: 5,
                    Code: 'occaecati',
                    Title: 'Enim Aut Labore Provident Et',
                    Name: 'consequuntur',
                    Position: 'facilis',
                    MarketingGroup: 'ad',
                    MarketingCode: 'et',
                    Department: 'fuga'
                },
                {
                    id: 544,
                    Code: 'velit',
                    Title: 'Molestiae Asperiores Et Et Est',
                    Name: 'ratione',
                    Position: 'dolore',
                    MarketingGroup: 'labore',
                    MarketingCode: 'ut',
                    Department: 'praesentium'
                },
                {
                    id: 138,
                    Code: 'consequuntur',
                    Title: 'Quaerat Nihil Praesentium',
                    Name: 'voluptates',
                    Position: 'quia',
                    MarketingGroup: 'aperiam',
                    MarketingCode: 'ut',
                    Department: 'mollitia'
                },
                {
                    id: 469,
                    Code: 'impedit',
                    Title: 'Voluptatum Itaque Dolore Dolorem Accusamus',
                    Name: 'est',
                    Position: 'est',
                    MarketingGroup: 'nobis',
                    MarketingCode: 'repudiandae',
                    Department: 'quis'
                },
                {
                    id: 393,
                    Code: 'iste',
                    Title: 'Neque Veritatis Maiores Similique Dolorem',
                    Name: 'nostrum',
                    Position: 'nostrum',
                    MarketingGroup: 'consequatur',
                    MarketingCode: 'quos',
                    Department: 'aperiam'
                },
                {
                    id: 390,
                    Code: 'maxime',
                    Title: 'Amet Et Suscipit Minima',
                    Name: 'corrupti',
                    Position: 'ullam',
                    MarketingGroup: 'atque',
                    MarketingCode: 'ab',
                    Department: 'maiores'
                },
                {
                    id: 127,
                    Code: 'iste',
                    Title: 'Eveniet Eius Distinctio Nulla',
                    Name: 'explicabo',
                    Position: 'blanditiis',
                    MarketingGroup: 'praesentium',
                    MarketingCode: 'nam',
                    Department: 'sint'
                },
                {
                    id: 323,
                    Code: 'est',
                    Title: 'Deleniti Ab Est',
                    Name: 'et',
                    Position: 'eligendi',
                    MarketingGroup: 'aut',
                    MarketingCode: 'repellat',
                    Department: 'adipisci'
                },
                {
                    id: 390,
                    Code: 'laboriosam',
                    Title: 'Fuga Similique Ut Vitae Accusantium',
                    Name: 'ab',
                    Position: 'voluptatem',
                    MarketingGroup: 'quis',
                    MarketingCode: 'ipsam',
                    Department: 'nihil'
                },
                {
                    id: 699,
                    Code: 'quidem',
                    Title: 'Vel Non',
                    Name: 'voluptas',
                    Position: 'quibusdam',
                    MarketingGroup: 'amet',
                    MarketingCode: 'molestiae',
                    Department: 'nemo'
                },
                {
                    id: 49,
                    Code: 'est',
                    Title: 'Officia Quia Voluptates',
                    Name: 'voluptate',
                    Position: 'officiis',
                    MarketingGroup: 'dignissimos',
                    MarketingCode: 'voluptate',
                    Department: 'sit'
                },
                {
                    id: 38,
                    Code: 'repellendus',
                    Title: 'Veniam Qui Dolorem',
                    Name: 'id',
                    Position: 'minus',
                    MarketingGroup: 'maxime',
                    MarketingCode: 'qui',
                    Department: 'sunt'
                },
                {
                    id: 292,
                    Code: 'architecto',
                    Title: 'Cum Magnam Rerum Tempora',
                    Name: 'et',
                    Position: 'in',
                    MarketingGroup: 'sunt',
                    MarketingCode: 'dolores',
                    Department: 'nesciunt'
                },
                {
                    id: 925,
                    Code: 'consequatur',
                    Title: 'Eveniet Eos',
                    Name: 'ut',
                    Position: 'ea',
                    MarketingGroup: 'omnis',
                    MarketingCode: 'minima',
                    Department: 'quis'
                },
                {
                    id: 905,
                    Code: 'voluptatem',
                    Title: 'Aut Ipsam Nulla Voluptatum Nisi',
                    Name: 'porro',
                    Position: 'ut',
                    MarketingGroup: 'magni',
                    MarketingCode: 'qui',
                    Department: 'esse'
                },
                {
                    id: 526,
                    Code: 'quia',
                    Title: 'Maxime Hic Exercitationem Sit Sint',
                    Name: 'sed',
                    Position: 'ut',
                    MarketingGroup: 'ullam',
                    MarketingCode: 'ad',
                    Department: 'sint'
                },
                {
                    id: 530,
                    Code: 'suscipit',
                    Title: 'Et Laborum Quas Optio',
                    Name: 'aspernatur',
                    Position: 'aperiam',
                    MarketingGroup: 'neque',
                    MarketingCode: 'atque',
                    Department: 'deleniti'
                },
                {
                    id: 756,
                    Code: 'ullam',
                    Title: 'Aut Repudiandae Sint Quos Voluptatem',
                    Name: 'at',
                    Position: 'inventore',
                    MarketingGroup: 'ut',
                    MarketingCode: 'quas',
                    Department: 'dolorum'
                },
                {
                    id: 391,
                    Code: 'ad',
                    Title: 'Fugit Quasi Voluptate Aut Consequatur',
                    Name: 'deserunt',
                    Position: 'pariatur',
                    MarketingGroup: 'rem',
                    MarketingCode: 'nihil',
                    Department: 'aspernatur'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});