//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTBLeasing.Report.extjs.WS_ActiveDirectory {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_ActiveDirectory.IWS_LoginAD")]
    public interface IWS_LoginAD {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:WS_LoginADIntf-IWS_LoginAD) of message LoginADRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:WS_LoginADIntf-IWS_LoginAD#LoginAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        KTBLeasing.Report.extjs.WS_ActiveDirectory.LoginADResponse LoginAD(KTBLeasing.Report.extjs.WS_ActiveDirectory.LoginADRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAD", WrapperNamespace="urn:WS_LoginADIntf-IWS_LoginAD", IsWrapped=true)]
    public partial class LoginADRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string oUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string oPassword;
        
        public LoginADRequest() {
        }
        
        public LoginADRequest(string oUser, string oPassword) {
            this.oUser = oUser;
            this.oPassword = oPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginADResponse", WrapperNamespace="urn:WS_LoginADIntf-IWS_LoginAD", IsWrapped=true)]
    public partial class LoginADResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public LoginADResponse() {
        }
        
        public LoginADResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWS_LoginADChannel : KTBLeasing.Report.extjs.WS_ActiveDirectory.IWS_LoginAD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_LoginADClient : System.ServiceModel.ClientBase<KTBLeasing.Report.extjs.WS_ActiveDirectory.IWS_LoginAD>, KTBLeasing.Report.extjs.WS_ActiveDirectory.IWS_LoginAD {
        
        public WS_LoginADClient() {
        }
        
        public WS_LoginADClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_LoginADClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_LoginADClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_LoginADClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KTBLeasing.Report.extjs.WS_ActiveDirectory.LoginADResponse KTBLeasing.Report.extjs.WS_ActiveDirectory.IWS_LoginAD.LoginAD(KTBLeasing.Report.extjs.WS_ActiveDirectory.LoginADRequest request) {
            return base.Channel.LoginAD(request);
        }
        
        public string LoginAD(string oUser, string oPassword) {
            KTBLeasing.Report.extjs.WS_ActiveDirectory.LoginADRequest inValue = new KTBLeasing.Report.extjs.WS_ActiveDirectory.LoginADRequest();
            inValue.oUser = oUser;
            inValue.oPassword = oPassword;
            KTBLeasing.Report.extjs.WS_ActiveDirectory.LoginADResponse retVal = ((KTBLeasing.Report.extjs.WS_ActiveDirectory.IWS_LoginAD)(this)).LoginAD(inValue);
            return retVal.@return;
        }
    }
}
